blank_issues_enabled: false

contact_links:
  - name: Bug or enhancement in BlockNote core
    url: https://github.com/TypeCellOS/BlockNote/issues
    about: Report a bug or suggest an enhancement in the BlockNote core code repository.
