blank_issues_enabled: false

contact_links:
  - name: Report a bug
    url: https://github.com/TypeCellOS/BlockNote/issues
    about: Report a bug in the BlockNote code repository.
  - name: Suggest an enhancement
    url: https://github.com/TypeCellOS/BlockNote/discussions/categories/ideas-enhancements
    about: Share feature ideas, enhancement suggestions, or other ideas for the BlockNote project.